version: '3.2'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    command:
      - ./run.sh
